server:
    port: 3333

#spring:
#    application: 
#        name: sadr-service

logging:
    level:
        root: 'INFO'
    #file: logs/${spring.application.name}.log
    #level:
    #    org.springframework.cloud: 'DEBUG'
    #    com.luishuapaya: 'DEBUG'